version: '3'

services:
  redis:
    # keydb is a performant drop-in replacement for redis
    image: eqalpha/keydb:alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  tunnel-server:
    build: .
    expose:
      - "80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # - REDIS_PASSWORD=your_password_if_needed
    depends_on:
      - redis

volumes:
  redis_data:
