version: '3'

services:
  redis:
    # keydb is a performant drop-in replacement for redis
    image: eqalpha/keydb:alpine
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  tunnel-server:
    build: .
    expose:
      - "80"
    environment:
      # redis connection
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      # inherited
      - REDIS_POOL_SIZE
      - REDIS_POOL_KEEPALIVE
      - TUNNEL_ACCESS_TOKEN
      - TUNNEL_MAXLEN
      - TUNNEL_BACKPRESSURE
      - TUNNEL_MAX_POLL_TIMEOUT
      - TUNNEL_DEFAULT_POLL_TIMEOUT
      - TUNNEL_DEFAULT_CONTENT_TYPE
    depends_on:
      - redis

volumes:
  redis_data:
