version: '3'

services:
  redis:
    image: eqalpha/keydb:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  tunnel-server:
    build: .
    ports:
      - "8080:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TUNNEL_ACCESS_TOKEN=thisisasecret
      - TUNNEL_SIGNATURE_SECRET=octopusatecat
      - TUNNEL_DEMO_ID=demo
    depends_on:
      - redis
    # mount lua dir and disable cache for faster development
    volumes:
      - ./src:/usr/local/openresty/lua
      - ./conf/conf.d/dev.conf:/etc/nginx/conf.d/dev.conf
      - ./demo:/var/www/demo

volumes:
  redis_data:
